baseURL = "https://450dsa.bytezone.in/"
languageCode = "en-us"
title = "450 DSA Cracker"
enableRobotsTXT = true

[params]
  description = "A comprehensive collection of 450 DSA problems to help you ace your coding interviews"
  author = "ByteZone"

  [params.seo]
    title = "450 DSA Cracker - Prepare for Coding Interviews"
    description = "Track your progress through 450 essential Data Structures and Algorithms problems to crack your coding interviews"
    keywords = "DSA, data structures, algorithms, coding interview, programming problems, interview preparation"

# Optional: Add Google Analytics or other custom params as needed
# [params.analytics]
#   googleAnalytics = "UA-XXXXXXXXX-X"

[markup]
  [markup.highlight]
    style = "monokai"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[build]
  useResourceCacheWhen = "always"

[outputs]
  home = ["HTML", "RSS", "JSON"]
