baseURL: "https://450dsa.bytezone.in/"
languageCode: "en-us"
title: "450 DSA Cracker"
enableRobotsTXT: true

params:
  description: "A comprehensive collection of 450 DSA problems to help you ace your coding interviews"
  author: "ByteZone"
  
  # SEO
  seo:
    title: "450 DSA Cracker - Prepare for Coding Interviews"
    description: "Track your progress through 450 essential Data Structures and Algorithms problems to crack your coding interviews"
    keywords: "DSA, data structures, algorithms, coding interview, programming problems, interview preparation"
